<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.3.12 setup script
 * Date: Sat, 14 Mar 2015 18:01:56 +0100
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'rh_apache';
$cfg['Servers'][$i]['password'] = 'Ideur0047';

/* End of servers configuration */

$cfg['blowfish_secret'] = '55046784671395.53830489';
$cfg['DefaultLang'] = 'de';
$cfg['ServerDefault'] = 1;
$cfg['ShowDbStructureCreation'] = true;
$cfg['Import']['charset'] = 'utf-8';
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>